const express = require('express');
const cors = require('cors');
const axios = require('axios');

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json());

const DELHIVERY_TOKEN = '73634895415b04ffca0b28a02595ec1ad7484386';

app.post('/get-rate', async (req, res) => {
  try {
    const {
      pickup_pincode,
      delivery_pincode,
      weight,
      length,
      breadth,
      height,
      declared_value
    } = req.body;

    const response = await axios.post(
      'https://ltl-clients-api.delhivery.com/freight/estimate',
      {
        pickup_pincode,
        delivery_pincode,
        packages: [
          {
            weight,
            length,
            breadth,
            height,
            declared_value
          }
        ],
        payment_mode: "prepaid"
      },
      {
        headers: {
          Authorization: `Token ${DELHIVERY_TOKEN}`,
          'Content-Type': 'application/json'
        }
      }
    );

    res.json(response.data);
  } catch (error) {
    console.error(error?.response?.data || error.message);
    res.status(500).json({ error: 'Failed to fetch rate estimate' });
  }
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
